--VIEW PARA CRIAR DIM_CANAL_VENDAS

SELECT A.SK_CLIENTE,D.SK_VENDEDOR,E.SK_GERENTE,F.SK_EMPRESA 
FROM DIM_CLIENTES A
 INNER JOIN  STG_CANAL_VENDAS_V_C B
	 ON A.COD_EMPRESA=B.COD_EMPRESA  
	 AND A.ID_CLIENTE=B.ID_CLIENTE
 INNER JOIN STG_CANAL_VENDAS_G_V C
	 ON A.COD_EMPRESA=C.COD_EMPRESA  
	 AND B.MATRICULA_VEND=C.MATRICULA_VEND
 INNER JOIN DIM_VENDEDOR D
	 ON A.COD_EMPRESA=D.COD_EMPRESA
	 AND C.MATRICULA_VEND=D.MATRICULA
 INNER JOIN DIM_GERENTES E
 ON A.COD_EMPRESA=E.COD_EMPRESA
	 AND C.MATRICULA_GER=E.MATRICULA
	 INNER JOIN DIM_EMPRESA F
 ON A.COD_EMPRESA=F.COD_EMPRESA
 