--SCRIPT PARA CRIAÇÃO DAS TABELAS DE DIMENSÃO.

USE DW
GO
--CADASTRO DE ESTADOS
CREATE TABLE DIM_UF(
	COD_UF varchar(2) NOT NULL PRIMARY KEY,
	NOME_UF varchar(30) NOT NULL
)
GO

--CADASTRO DE CIDADES
CREATE TABLE DIM_CIDADES(
	COD_CIDADE varchar(7) PRIMARY KEY NOT NULL,
	COD_UF varchar(2) NOT NULL,
	NOME_MUN varchar(50) NOT NULL
	)
GO

--CADASTRO DA EMPRESA
CREATE TABLE DIM_EMPRESA(
    SK_EMPRESA INT PRIMARY KEY NOT NULL,
	COD_EMPRESA int NOT NULL,
	NOME_EMPRESA varchar(50) NOT NULL,
	FANTASIA varchar(20) NOT NULL,
	CNPJ varchar(15) NOT NULL,
	ENDERECO varchar(50) NOT NULL,
	COD_CIDADE varchar(7) NOT NULL
	)
GO

--CADASTRO DE CLIENTES
CREATE TABLE DIM_CLIENTES(
    SK_CLIENTE INT NOT NULL PRIMARY KEY,
	COD_EMPRESA int NOT NULL,
	ID_CLIENTE int NOT NULL,
	RAZAO_CLIENTE varchar(100) NOT NULL,
	FANTASIA varchar(15) NOT NULL,
	ENDERECO varchar(50) NOT NULL,
	NRO varchar(10) NOT NULL,
	BAIRRO varchar(20) NOT NULL,
	COD_CIDADE varchar(7) NOT NULL,
	CEP varchar(8) NULL,
	CNPJ_CPF varchar(15) NULL,
	TIPO_CLIENTE char(1) NULL,
	DATA_CADASTRO datetime NOT NULL,
	SITUACAO char(1) NULL
)
GO

--CADASTRO DE FUNCIONARIOS
CREATE TABLE DIM_FUNCIONARIO(
    SK_FUNC INT NOT NULL PRIMARY KEY,
	COD_EMPRESA int NOT NULL,
	MATRICULA int NOT NULL,
	NOME varchar(50) NOT NULL,
	RG varchar(15) NOT NULL,
	CPF varchar(15) NOT NULL,
	ENDERECO varchar(50) NOT NULL,
	NUMERO varchar(10) NOT NULL,
	BAIRRO varchar(50) NOT NULL,
	COD_CIDADE varchar(7) NOT NULL,
	COD_CARGO int NOT NULL
	)
GO
--CADASTRO DE GERENTES
CREATE TABLE DIM_GERENTES(
    SK_GERENTE INT NOT NULL PRIMARY KEY,
	COD_EMPRESA int NOT NULL,
	MATRICULA int NOT NULL,
	NOME varchar(50) NOT NULL,
)
GO

--CADASTRO DE VENDEDOR
CREATE TABLE DIM_VENDEDOR(
    SK_VENDEDOR INT NOT NULL PRIMARY KEY,
	COD_EMPRESA int NOT NULL,
	MATRICULA int NOT NULL,
	NOME varchar(50) NOT NULL,
)
GO

--CADASTRO CONDIÇÃO DE PAGTO
CREATE TABLE DIM_COND_PAGTO(
	COD_PAGTO int NOT NULL PRIMARY KEY,
	NOME_CP varchar(50) NOT NULL,
)
GO
--CANAL DE VENDAS
CREATE TABLE DIM_CANAL_VENDAS(
    SK_CANAL INT NOT NULL PRIMARY KEY,
    SK_EMPRESA INT NOT NULL,
    SK_GERENTE INT NOT NULL,
	SK_VENDEDOR INT NOT NULL,
	SK_CLIENTE INT NOT NULL
	)
GO
--CADASTRO TIPO MATERIAL
CREATE TABLE DIM_TIPO_MAT(
    SK_TIP_MAT INT NOT NULL PRIMARY KEY,
	SK_EMPRESA int NOT NULL,
	--COD_EMPRESA int NOT NULL,
	COD_TIP_MAT int NOT NULL,
	DESC_TIP_MAT varchar(20) NOT NULL
	)
GO


--CADASTRO LINHA DE PRODUTO
CREATE TABLE DIM_LINHA_PRODUTO(
	SK_LINHA_PROD INT NOT NULL PRIMARY KEY,
	SK_EMPRESA int NOT NULL,
	--COD_EMPRESA int NOT NULL,
	COD_LINHA int NOT NULL,
	DESC_LINHA varchar(50) NOT NULL
	)
GO
--CADASTRO SUB_CATEGORIA DE PROD.
CREATE TABLE DIM_SUB_CATEGORIA(
   	SK_SUB_CATEG INT NOT NULL PRIMARY KEY,
	SK_EMPRESA int NOT NULL,
	--COD_EMPRESA int NOT NULL,
	COD_CATEGORIA int NOT NULL,
	DESC_CATEGORIA varchar(50) NOT NULL
	)
GO

--CADASTRO DE MATERIAL
CREATE TABLE DIM_MATERIAL(
	SK_MAT int NOT NULL PRIMARY KEY,
	SK_EMPRESA int NOT NULL,
	SK_TIP_MAT int NOT NULL,
	SK_LINHA_PROD int NOT NULL,
	SK_SUB_CATEG int NOT NULL,
	COD_EMPRESA int NOT NULL,
	COD_MAT int NOT NULL,
	DESCRICAO varchar(50) NOT NULL,
	PRECO_UNIT decimal(10, 2) NOT NULL
--	COD_TIP_MAT int NOT NULL,
--	COD_LINHA int NULL,
--	COD_CATEGORIA int NULL
)

--CADASTRO DE CUSTO DO MATERIAL
CREATE TABLE DIM_MATERIAL_CUSTO(
    SK_EMPRESA int NOT NULL,
   	SK_MAT int NOT NULL,
	--COD_EMPRESA int NOT NULL,
	--COD_MAT int NOT NULL,
	CUSTO_MEDIO int NULL,
	DATA_INI date NOT NULL,
	DATA_FIM date NULL,
	PRIMARY KEY(SK_EMPRESA,SK_MAT,DATA_INI)
	)


