--FATO VENDA
USE DW
GO
--FATO ORCAMENTO
CREATE TABLE FATO_VENDA(
	SK_EMPRESA int NOT NULL,
	NUM_NF int NOT NULL,
	TIP_NF char(1) NOT NULL,
	COD_CFOP varchar(5) NOT NULL,
	SK_CLIENTE int NOT NULL,
	COD_PAGTO int NOT NULL,
	DATA_EMISSAO datetime NOT NULL,
	DATA_ENTREGA date NOT NULL,
	TOTAL_NF decimal(10, 2) NULL,
	SEQ_MAT int NOT NULL,
	SK_MAT int NOT NULL,
	QTD decimal(10, 2) NULL,
	VAL_UNIT decimal(10, 2) NOT NULL,
	VAL_CUSTO decimal(10, 2) NULL,
PRIMARY KEY (SK_EMPRESA,NUM_NF,SEQ_MAT))
GO

--FATO ORCAMENTO
CREATE TABLE FATO_META(
	SK_EMPRESA int NOT NULL,
	SK_VENDEDOR int NOT NULL,
	DATA_REF date NOT NULL,
	VALOR decimal(10, 2) NULL,
PRIMARY KEY CLUSTERED (SK_EMPRESA,SK_VENDEDOR,DATA_REF))

