--UPDATE 1 COM CUSTO
UPDATE FATO_VENDA SET VAL_CUSTO=(SELECT A.CUSTO_MEDIO 
FROM DIM_MATERIAL_CUSTO A
WHERE FATO_VENDA.SK_EMPRESA=A.SK_EMPRESA
AND FATO_VENDA.SK_MAT=A.SK_MAT
AND CAST(FATO_VENDA.DATA_EMISSAO AS DATE) >=A.DATA_INI 
AND CAST(FATO_VENDA.DATA_EMISSAO AS DATE)<=A.DATA_FIM)

--UPDATE 2 CUSTO ORIGEM CADASTRO
UPDATE FATO_VENDA SET VAL_CUSTO=(SELECT A.PRECO_UNIT*.90
FROM DIM_MATERIAL A
WHERE FATO_VENDA.SK_EMPRESA=A.SK_EMPRESA
AND FATO_VENDA.SK_MAT=A.SK_MAT)
WHERE FATO_VENDA.VAL_CUSTO IS NULL
